/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import db.DBManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nxs4z3
 */
public class AdvertisementsFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdvertisementsFrame
     */
    DBManager DB;
    //String Advertisement_ID;
    
    String User_ID;
    
    //columns for advertisements_table
    String[] columnsAdv=new String[] {
         "Title", "Description", "Price", "Date"
    };
    
    //columns for myAdvertisements_table
    String[] columnsMyAdv=new String[] {
        "ID", "Title", "Description", "Price", "Status", "Date"
    };
    
    public AdvertisementsFrame(DBManager DB, String username) {
       
        
        this.setTitle("Username: " + username);
        this.DB=DB;
        this.User_ID = username;
        initComponents();
        
        
        
        /**
        int category = categoryDrop.getSelectedIndex();
        int date = periodDrop.getSelectedIndex();
        String categoryType = "CAT";
        String period = "3";
        //---------------------------------------------------
        
 
        switch(category){
            case(0):
            {
                categoryType = "All";
                break;
            }
            case(1):
            {
                categoryType = "CAT";
                break;
            }
            case(2):
            {
                categoryType = "HOU";
                break;
            }
            case(3):
            {
                categoryType = "ELC";
                break;
            }
            case(4):
            {
                categoryType = "CCA";
                break;
            }
         
        }
        
        switch(date){
            case(0):
            {
                period = "3";
                break;
            }
            case(1):
            {
                period = "6";
                break;
            }
            case(2):
            {
                period = "12";
                break;
            }
            case(3):
            {
                period = "ALL";
                break;
            }
         
        }
        */
        //---------------------------------------------------
        
        this.populate_advertisements_table();
        this.populate_myAdvertisements_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        advPanel = new javax.swing.JPanel();
        categoryDrop = new javax.swing.JComboBox<>();
        periodDrop = new javax.swing.JComboBox<>();
        CategoryLabel = new javax.swing.JLabel();
        PeriodLabel = new javax.swing.JLabel();
        titleDescText = new javax.swing.JTextField();
        TitleDescLabel = new javax.swing.JLabel();
        goFilterButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        advertisements_table = new javax.swing.JTable();
        myAdvPanel = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        myAdvertisements_table = new javax.swing.JTable();
        addAdvButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        categoryDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "CAT", "HOU", "ELC", "CCA" }));

        periodDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Last 3 months", "Last 6 months", "Last 12 months", "Life" }));

        CategoryLabel.setText("Category");

        PeriodLabel.setText("Period");

        TitleDescLabel.setText("Title, Description");

        goFilterButton.setText("GO");

        advertisements_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "Description", "Price", "Date"
            }
        ));
        advertisements_table.setName("advertisements_table"); // NOI18N
        jScrollPane1.setViewportView(advertisements_table);

        javax.swing.GroupLayout advPanelLayout = new javax.swing.GroupLayout(advPanel);
        advPanel.setLayout(advPanelLayout);
        advPanelLayout.setHorizontalGroup(
            advPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(advPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoryLabel))
                .addGap(48, 48, 48)
                .addGroup(advPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(periodDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(advPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleDescLabel)
                    .addGroup(advPanelLayout.createSequentialGroup()
                        .addComponent(titleDescText, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(goFilterButton)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        advPanelLayout.setVerticalGroup(
            advPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryLabel)
                    .addComponent(PeriodLabel)
                    .addComponent(TitleDescLabel))
                .addGap(4, 4, 4)
                .addGroup(advPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleDescText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goFilterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Advertisements", advPanel);

        editButton.setText("Edit");

        deleteButton.setText("Delete");

        myAdvertisements_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Description", "Price", "Status", "Date"
            }
        ));
        jScrollPane2.setViewportView(myAdvertisements_table);

        javax.swing.GroupLayout myAdvPanelLayout = new javax.swing.GroupLayout(myAdvPanel);
        myAdvPanel.setLayout(myAdvPanelLayout);
        myAdvPanelLayout.setHorizontalGroup(
            myAdvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myAdvPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(myAdvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myAdvPanelLayout.createSequentialGroup()
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myAdvPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        myAdvPanelLayout.setVerticalGroup(
            myAdvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myAdvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myAdvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("My Advertisements", myAdvPanel);

        addAdvButton.setText("Add Advertisement");
        addAdvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdvButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addAdvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addAdvButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*~~~~~~~~~~ Add Advertisement ~~~~~~~~~~*/
    private void addAdvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdvButtonActionPerformed
        // TODO add your handling code here:
        //FIXME: check name for add advertisement screen
        //AddAdvertisementFrame addFrame=new AddAdvertisementFrame(this,DB,Advertisement_ID);
        //addFrame.setVisible(true);
    }//GEN-LAST:event_addAdvButtonActionPerformed

    
    /*~~~~~~~~~~ Advertisements Tab (filter category, filter period, filter title) ~~~~~~~~~~*/
    private void categoryDropActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }
    
    private void periodDropActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }
    
     private void goFilterActionPerformed(java.awt.event.ActionEvent evt) {
         // TODO add your handling code here:
     }
    
    /*~~~~~~~~~~ My Advertisements Tab (edit, delete) ~~~~~~~~~~*/
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        int row = this.myAdvertisements_table.getSelectedRow();
        if (row >=0 ) {
            String AdvTitle=(String)myAdvertisements_table.getValueAt(row, 1);
            String AdvDetails=(String)myAdvertisements_table.getValueAt(row, 2);
            String Price=(String)myAdvertisements_table.getValueAt(row, 3);
            
            //FIXME: should they be able to edit the date
            String AdvDateTime=(String)myAdvertisements_table.getValueAt(row, 5);
            
            //FIXME: check what the method in DB is named
            //DB.changeAdvertisementStatus(AdvTitle, AdvDetails, Price);
        }
    } 
    
     private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
         // TODO add your handling code here:
     }
     
    /*~~~~~~~~~~ Populate Functions ~~~~~~~~~~*/
    public void populate_advertisements_table() {
        
         
        Object[][] ads = DB.getAdevertisements();
        this.advertisements_table.setModel(new DefaultTableModel(ads,columnsAdv));
        
        //FIXME: check DB method name
        //FIXME: how to ensure only advertisements that are active in display
        //Object[][] Advertisements_data=DB.getAdvertisements(Advertisement_ID);
        //this.advertisements_table.setModel(new DefaultTableModel(Advertisements_data, columnsAdv));
    }
    
    public void populate_myAdvertisements_table() {
        Object[][] usrAds = DB.getUserAdevertisements(User_ID);
        this.myAdvertisements_table.setModel(new DefaultTableModel(usrAds,columnsMyAdv));

        
        //FIXME: check DB method name 
        //FIXME: how to ensure only advertisments from a certain username in display
        //Object[][] myAdvertisements_data=DB.getAdvertisements(Advertisement_ID);
        //this.myAdvertisements_table.setModel(new DefaultTableModel(myAdvertisements_data, columnsMyAdv));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvertisementsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvertisementsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvertisementsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvertisementsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdvertisementsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoryLabel;
    private javax.swing.JLabel PeriodLabel;
    private javax.swing.JLabel TitleDescLabel;
    private javax.swing.JButton addAdvButton;
    private javax.swing.JPanel advPanel;
    private javax.swing.JTable advertisements_table;
    private javax.swing.JComboBox<String> categoryDrop;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton goFilterButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JPanel myAdvPanel;
    private javax.swing.JTable myAdvertisements_table;
    private javax.swing.JComboBox<String> periodDrop;
    private javax.swing.JTextField titleDescText;
    // End of variables declaration//GEN-END:variables
}
